apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vessel-routing-client
  namespace: vesops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: vessel-routing.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vessel-routing-client
                port:
                  number: 80
