apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vesops

resources:
  - namespace.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - nodeport.yaml
  - hpa.yaml

images:
  - name: vessel-routing-client
    newName: localhost:5000/vessel-routing
    newTag: latest
