#!/bin/bash
# =============================================================================
# create-secrets.sh — Collect secrets, write base64 to secret.yaml, apply to k8s
#
# Usage:
#   ./scripts/create-secrets.sh
# =============================================================================
set -e

NAMESPACE="vesops"
SECRET_NAME="vessel-routing-secrets"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SECRET_FILE="${PROJECT_DIR}/k8s/dev/secret.yaml"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

echo "============================================"
echo " vessel-routing-client secret setup"
echo " Namespace : ${NAMESPACE}"
echo "============================================"
echo ""

# ---------------------------------------------------------------------------
# Collect ABB OAuth2 credentials
# ---------------------------------------------------------------------------
log_info "ABB OAuth2 credentials (outbound — used to call ABB routing API)"
echo ""

read -p "  OAUTH_CLIENT_ID     : " OAUTH_CLIENT_ID
[ -z "${OAUTH_CLIENT_ID}" ] && { log_error "OAUTH_CLIENT_ID cannot be empty"; exit 1; }

read -s -p "  OAUTH_CLIENT_SECRET : " OAUTH_CLIENT_SECRET
echo ""
[ -z "${OAUTH_CLIENT_SECRET}" ] && { log_error "OAUTH_CLIENT_SECRET cannot be empty"; exit 1; }

echo ""

# ---------------------------------------------------------------------------
# Collect inbound API credentials
# ---------------------------------------------------------------------------
log_info "Inbound API credentials (used by callers to authenticate with this service)"
echo ""

read -p "  API_USERNAME        : " API_USERNAME
[ -z "${API_USERNAME}" ] && { log_error "API_USERNAME cannot be empty"; exit 1; }

read -s -p "  API_PASSWORD        : " API_PASSWORD
echo ""
[ -z "${API_PASSWORD}" ] && { log_error "API_PASSWORD cannot be empty"; exit 1; }

# Generate bcrypt hash
log_info "Generating bcrypt hash for API_PASSWORD..."
API_PASSWORD_HASH=$(python3 -c "from passlib.hash import bcrypt; print(bcrypt.hash('${API_PASSWORD}'))" 2>/dev/null)
[ -z "${API_PASSWORD_HASH}" ] && { log_error "Failed to generate bcrypt hash. Run: pip install passlib[bcrypt]"; exit 1; }
log_info "bcrypt hash generated."

echo ""

# ---------------------------------------------------------------------------
# JWT secret
# ---------------------------------------------------------------------------
log_info "JWT signing secret"
echo ""
read -p "  JWT_SECRET_KEY (leave blank to auto-generate) : " JWT_SECRET_KEY
if [ -z "${JWT_SECRET_KEY}" ]; then
    JWT_SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")
    log_info "Auto-generated JWT_SECRET_KEY."
fi

echo ""

# ---------------------------------------------------------------------------
# Confirm
# ---------------------------------------------------------------------------
echo "============================================"
echo " Summary"
echo "  OAUTH_CLIENT_ID     : ${OAUTH_CLIENT_ID}"
echo "  OAUTH_CLIENT_SECRET : ****"
echo "  API_USERNAME        : ${API_USERNAME}"
echo "  API_PASSWORD_HASH   : (bcrypt)"
echo "  JWT_SECRET_KEY      : ****"
echo "============================================"
echo ""
read -p "Write to ${SECRET_FILE} and apply to namespace '${NAMESPACE}'? [y/N] " CONFIRM
if [[ "${CONFIRM}" != "y" && "${CONFIRM}" != "Y" ]]; then
    log_warn "Aborted. No changes made."
    exit 0
fi

# ---------------------------------------------------------------------------
# Base64 encode all values
# ---------------------------------------------------------------------------
b64() { echo -n "$1" | base64 | tr -d '\n'; }

B64_OAUTH_CLIENT_ID=$(b64 "${OAUTH_CLIENT_ID}")
B64_OAUTH_CLIENT_SECRET=$(b64 "${OAUTH_CLIENT_SECRET}")
B64_API_USERNAME=$(b64 "${API_USERNAME}")
B64_API_PASSWORD_HASH=$(b64 "${API_PASSWORD_HASH}")
B64_JWT_SECRET_KEY=$(b64 "${JWT_SECRET_KEY}")

# ---------------------------------------------------------------------------
# Write secret.yaml with real base64 values
# ---------------------------------------------------------------------------
log_info "Writing base64-encoded secrets to ${SECRET_FILE}..."

cat > "${SECRET_FILE}" <<EOF
# Auto-generated by create-secrets.sh — DO NOT commit this file with real values
apiVersion: v1
kind: Secret
metadata:
  name: ${SECRET_NAME}
  namespace: ${NAMESPACE}
type: Opaque
data:
  OAUTH_CLIENT_ID: ${B64_OAUTH_CLIENT_ID}
  OAUTH_CLIENT_SECRET: ${B64_OAUTH_CLIENT_SECRET}
  API_USERNAME: ${B64_API_USERNAME}
  API_PASSWORD_HASH: ${B64_API_PASSWORD_HASH}
  JWT_SECRET_KEY: ${B64_JWT_SECRET_KEY}
EOF

log_info "secret.yaml updated."

# ---------------------------------------------------------------------------
# Apply to Kubernetes
# ---------------------------------------------------------------------------
log_info "Applying secret to namespace '${NAMESPACE}'..."
kubectl apply -f "${SECRET_FILE}"
log_info "Secret applied successfully."

echo ""
log_info "To verify:"
echo "  kubectl get secret ${SECRET_NAME} -n ${NAMESPACE}"
echo "  kubectl describe secret ${SECRET_NAME} -n ${NAMESPACE}"
